const CSRF = (
  <>
    {`
    1. What is CSRF?

        CSRF (Cross-Site Request Forgery) is a type of attack where:

        An attacker tricks a user’s browser into sending unwanted requests to a website where the user is already authenticated.

        For example: if a user is logged in to their banking site, a malicious site can trigger a money transfer request in the background without the user knowing.

        Problem: The server thinks the request is legitimate because the user is already authenticated via cookies/session.
            
    2. What is an Anti-Forgery Token?

        ASP.NET Core uses Anti-Forgery Tokens to prevent CSRF attacks.

        An anti-forgery token is a unique, secret value generated by the server and associated with the user’s session.

        The server checks the token on every state-changing request (like POST, PUT, DELETE) to ensure the request is coming from the legitimate user.
            
    3. How ASP.NET Core Implements Anti-Forgery
        A. In Razor Pages / MVC Forms

        In your view, include the token:

        <form method="post">
            @Html.AntiForgeryToken()
            <input type="text" name="Name" />
            <button type="submit">Submit</button>
        </form>

        @Html.AntiForgeryToken() injects a hidden input field like:

        <input name="__RequestVerificationToken" type="hidden" value="random_token_value" />
        
    4. On the controller action, validate automatically:

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SubmitForm(MyModel model)
        {
            // This code runs only if the token is valid
            return Ok();
        }

    -----------------------------1. Dot Net Core API + React----------------------------------
    
    2. Configure Anti-Forgery in Program.cs
        builder.Services.AddControllers();
        builder.Services.AddAntiforgery(options =>
        {
            options.HeaderName = "X-CSRF-TOKEN"; // Header name for AJAX
        });

        var app = builder.Build();

        app.UseAuthentication();
        app.UseAuthorization();

        app.MapControllers();
        app.Run();

    3. Generate CSRF Token in Controller

        using Microsoft.AspNetCore.Antiforgery;
        using Microsoft.AspNetCore.Mvc;

        [ApiController]
        [Route("api/[controller]")]
        public class CsrfController : ControllerBase
        {
            private readonly IAntiforgery _antiforgery;

            public CsrfController(IAntiforgery antiforgery)
            {
                _antiforgery = antiforgery;
            }

            [HttpGet("token")]
            public IActionResult GetToken()
            {
                var tokens = _antiforgery.GetAndStoreTokens(HttpContext);
                return Ok(new { csrfToken = tokens.RequestToken });
            }
        }

    4. Validate CSRF Token in Middleware

        You can create a custom middleware for CSRF validation on state-changing requests (POST/PUT/DELETE):

        public class CsrfMiddleware
        {
            private readonly RequestDelegate _next;
            private readonly IAntiforgery _antiforgery;

            public CsrfMiddleware(RequestDelegate next, IAntiforgery antiforgery)
            {
                _next = next;
                _antiforgery = antiforgery;
            }

            public async Task InvokeAsync(HttpContext context)
            {
                if (HttpMethods.IsPost(context.Request.Method) ||
                    HttpMethods.IsPut(context.Request.Method) ||
                    HttpMethods.IsDelete(context.Request.Method))
                {
                    try
                    {
                        await _antiforgery.ValidateRequestAsync(context);
                    }
                    catch
                    {
                        context.Response.StatusCode = 400;
                        await context.Response.WriteAsync("Invalid CSRF Token");
                        return;
                    }
                }

                await _next(context);
            }
        }


        Add the middleware after authentication in Program.cs:

        app.UseAuthentication();
        app.UseMiddleware<CsrfMiddleware>();
        app.UseAuthorization();

    5. Front-End: Include CSRF Token

        Get the token from /api/csrf/token

        Include it in headers for requests:

        const csrfToken = await fetch('/api/csrf/token').then(res => res.json());

        fetch('/api/data', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'Authorization': 6Bearer 7{jwtToken}6,  put carret instad of 6 and dowler instead 7
                'X-CSRF-TOKEN': csrfToken.csrfToken
            },
            body: JSON.stringify({ name: 'Test' })
        });

       -----------------Create custom hook in React to get csrfToken


       Call this after sign-in or on app bootstrap and attach it to all requests.

       eact + fetch (hook):

            // useCsrf.js
            import { useEffect, useState } from "react";

            export function useCsrf() {
            const [csrfToken, setCsrfToken] = useState(null);

            useEffect(() => {
                async function getToken() {
                // include credentials if auth uses cookies
                const res = await fetch("/api/csrf/token", { credentials: "include" });
                if (!res.ok) return;
                const json = await res.json();
                setCsrfToken(json.csrfToken);
                }
                getToken();
            }, []);

            return csrfToken;
            }

        Use it when sending POST/PUT/DELETE:

        import { useCsrf } from "./useCsrf";

        function createItem(data, jwt) {
        const csrfToken = useCsrf(); // or get from context/state

        // Example fetch
        return fetch("/api/items", {
            method: "POST",
            credentials: "include",              // if cookies are used
            headers: {
            "Content-Type": "application/json",
            Authorization: 6Bearer 7{jwt}6,    // if using JWT header
            "X-CSRF-TOKEN": csrfToken || ""    // antiforgery header name your server expects
            },
            body: JSON.stringify(data)
        });
        }
        
    Use CSRF Token in POST Request

        Once the token is available, include it in the header:

        import React, { useState } from "react";
        import { useCsrfToken } from "./hooks/useCsrfToken";

        export default function App() {
        const csrfToken = useCsrfToken();
        const [response, setResponse] = useState("");

        const handleSubmit = async () => {
            const res = await fetch("https://localhost:5001/api/data", {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "X-CSRF-TOKEN": csrfToken, // must match backend HeaderName
            },
            credentials: "include",
            body: JSON.stringify({ name: "Khalid" }),
            });

            const data = await res.json();
            setResponse(JSON.stringify(data));
        };

        return (
            <div style={{ padding: "2rem" }}>
            <h2>CSRF Token Demo</h2>
            <button onClick={handleSubmit} disabled={!csrfToken}>
                Send Secure POST Request
            </button>
            <p>{response}</p>
            </div>
        );
        }






    `}
  </>
);

export default CSRF;
